<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-10T16:44:14 IST" name="Default suite" finished-at="2025-10-10T16:44:17 IST" duration-ms="2240">
    <groups>
    </groups>
    <test started-at="2025-10-10T16:44:14 IST" name="Default test" finished-at="2025-10-10T16:44:17 IST" duration-ms="2240">
      <class name="advance_reports.SauceDemo">
        <test-method is-config="true" signature="repConfig()[pri:0, instance:advance_reports.SauceDemo@2a5c8d3f]" started-at="2025-10-10T16:44:14 IST" name="repConfig" finished-at="2025-10-10T16:44:14 IST" duration-ms="253" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- repConfig -->
        <test-method is-config="true" signature="openBro()[pri:0, instance:advance_reports.SauceDemo@2a5c8d3f]" started-at="2025-10-10T16:44:14 IST" name="openBro" finished-at="2025-10-10T16:44:16 IST" duration-ms="1601" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBro -->
        <test-method signature="failing()[pri:0, instance:advance_reports.SauceDemo@2a5c8d3f]" started-at="2025-10-10T16:44:16 IST" name="failing" finished-at="2025-10-10T16:44:16 IST" duration-ms="364" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertFalse(Assert.java:79)
at org.testng.Assert.assertFalse(Assert.java:89)
at advance_reports.SauceDemo.failing(SauceDemo.java:59)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failing -->
        <test-method signature="passing()[pri:0, instance:advance_reports.SauceDemo@2a5c8d3f]" started-at="2025-10-10T16:44:16 IST" name="passing" finished-at="2025-10-10T16:44:16 IST" duration-ms="36" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- passing -->
        <test-method signature="skipping()[pri:0, instance:advance_reports.SauceDemo@2a5c8d3f]" started-at="2025-10-10T16:44:17 IST" name="skipping" finished-at="2025-10-10T16:44:17 IST" depends-on-methods="advance_reports.SauceDemo.failing" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method advance_reports.SauceDemo.skipping() on instance advance_reports.SauceDemo@2a5c8d3f depends on not successfully finished methods 
[advance_reports.SauceDemo.failing() on instance advance_reports.SauceDemo@2a5c8d3f]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method advance_reports.SauceDemo.skipping() on instance advance_reports.SauceDemo@2a5c8d3f depends on not successfully finished methods 
[advance_reports.SauceDemo.failing() on instance advance_reports.SauceDemo@2a5c8d3f]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- skipping -->
        <test-method is-config="true" signature="closeBro()[pri:0, instance:advance_reports.SauceDemo@2a5c8d3f]" started-at="2025-10-10T16:44:17 IST" name="closeBro" finished-at="2025-10-10T16:44:17 IST" duration-ms="195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBro -->
        <test-method is-config="true" signature="repBackup()[pri:0, instance:advance_reports.SauceDemo@2a5c8d3f]" started-at="2025-10-10T16:44:17 IST" name="repBackup" finished-at="2025-10-10T16:44:17 IST" duration-ms="383" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- repBackup -->
      </class> <!-- advance_reports.SauceDemo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
